### ISSUE TITLE
长时间运行后退出

### ISSUE THREAD

**Issue by jjwang** [jjwang/laibot#2]
错误提示为：

```
Traceback (most recent call last):
  File "jasper.py", line 156, in <module>
    app.run()
  File "jasper.py", line 125, in run
    conversation.handleForever()
  File "/home/pi/Desktop/work2017/jasper-client/client/conversation.py", line 27, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/Desktop/work2017/jasper-client/client/mic.py", line 141, in passiveListen
    data = stream.read(CHUNK)
  File "build/bdist.linux-armv7l/egg/pyaudio.py", line 608, in read
    """
IOError: [Errno -9981] Input overflowed
```

**Comment by jjwang** [comment]
加 chunk = stream.read(CHUNK_SIZE, exception_on_overflow=False) 解决。
